/* eslint-disable @typescript-eslint/no-unused-vars */
import { cookieToWeb3AuthState } from "@web3auth/modal";
import type { Metadata } from "next";
import { headers } from "next/headers";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Provider from "./components/provider";
import { BlockchainProvider } from "./context/DocContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// eslint-disable-next-line no-undef
export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const headersList = await headers();
  const web3authInitialState = cookieToWeb3AuthState(headersList.get('cookie'));
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider web3authInitialState={web3authInitialState}>
          <BlockchainProvider>
          {children}
          </BlockchainProvider>
          </Provider>
        {/* <Provider web3authInitialState={web3authInitialState}>{children}</Provider> */}
      </body>
    </html>
  );
}